TuReward/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from publicPanel import views

urlpatterns = [
    path('adminPage/', admin.site.urls, name='adminPage'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('publicPanel.urls')),
    path('users/', include('userPanel.urls')),
    path('administration/', include('adminPanel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminPanel/urls.py
from django.urls import path

from adminPanel import views
from .views import CreateNormalUserAPIView, RewardsAPIView, CheckCodeApiView, AddBusinessApiView, UpdatePersonalInfoApiView

app_name = 'adminPanel'

urlpatterns = [
    path('',views.index, name="home"),
    path('scan/',views.scan, name="scan"),
    #APIs
    path('create-normal-user/', CreateNormalUserAPIView.as_view(), name='create-normal-user'),
    path('rewards-api/', RewardsAPIView.as_view(), name='rewards-api'),
    path('check-code-api/', CheckCodeApiView.as_view(), name='check-code-api'),
    path('add-business-api/', AddBusinessApiView.as_view(), name='add-business-api'),
    path('update-personal-info-api/', UpdatePersonalInfoApiView.as_view(), name='update-personal-info-api'),
]

adminPanel/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.contrib.auth.hashers import make_password, is_password_usable, check_password
from .utils import generate_qr

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    NORMAL_USER = 'normal_user'
    ADMINISTRATOR = 'administrator'
    ACCOUNT_TYPE_CHOICES = [
        (NORMAL_USER, 'Normal_user'),
        (ADMINISTRATOR, 'Administrator'),
    ]
    code = models.CharField(max_length=15, unique=True, null=True)
    account_type = models.CharField(max_length=50, choices=ACCOUNT_TYPE_CHOICES,  db_index=True)
    qrCode = models.ImageField(upload_to='images/users/qr_codes', blank=True, null=True)
    
    def __str__(self):
        return self.username
    groups = models.ManyToManyField(
        Group,
        related_name='user_group',  
        blank=True,
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='user_permissions', 
        blank=True,
    )
    def save(self, *args, **kwargs):

        if self.pk:  
            current_password = CustomUser.objects.get(pk=self.pk).password
            if self.password != current_password and (not is_password_usable(self.password) or not check_password(self.password, self.password)):
                self.password = make_password(self.password)
                
        else:
            if self.password and not is_password_usable(self.password):
                self.password = make_password(self.password)

        if not self.qrCode:
                    qr_image = generate_qr(self.code)
                    self.qrCode.save(f'QR_code_{self.code}.png', qr_image, save=False)
                    
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

class Business(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=15, unique=True)
    qrCode = models.ImageField(upload_to='images/business/qr_codes', blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.qrCode:
            qr_image = generate_qr(self.code)
            self.qrCode.save(f'QR_code_{self.code}.png', qr_image, save=False)
        super().save(*args, **kwargs)
        
class UserBusinessRelation(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='business_relations')
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='user_relations')
    points = models.IntegerField(default=0)
    
    class Meta:
        unique_together = ['user', 'business'] 
        indexes = [
            models.Index(fields=['user']),
            models.Index(fields=['business']),
        ]
        
class Reward(models.Model):
    title = models.CharField(max_length=25)
    code = models.CharField(max_length=15, unique=True)
    points_requiered = models.PositiveIntegerField()
    description = models.TextField(max_length=250)
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='rewards',)
    qrCode = models.ImageField(upload_to='images/rewards/qr_codes', blank=True, null=True)
    
class Transaction(models.Model):
    title = models.CharField(max_length=20)
    amount = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True) 
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='transactions')
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='transactions',)

adminPanel/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomUserSerializer, RewardSerializer
from .models import CustomUser, Business, Reward, Transaction, UserBusinessRelation
from rest_framework.parsers import JSONParser, FormParser, MultiPartParser
import random
import string
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.utils import timezone
from datetime import datetime, timedelta
from django.db import transaction
from .utils import generate_qr

def is_admin(user):
    return user.is_authenticated and user.account_type == 'administrator'

def is_normal(user):
    return user.is_authenticated and user.account_type == 'normal_user'

@user_passes_test(is_admin)
def index(request):
    user = request.user
    related_businesses = Business.objects.filter(user_relations__user=user)

    businesses_with_rewards = {
        business: Reward.objects.filter(business=business).order_by('points_requiered')
        for business in related_businesses
    }

    context = {
        'user': user,
        'businesses_with_rewards': businesses_with_rewards,
        'user_business': related_businesses
    }
    return render(request, "adminIndex.html", context)

@user_passes_test(is_admin)
def scan(request):
    user = request.user

    related_business_relations = UserBusinessRelation.objects.filter(user=user).select_related('business')
    related_businesses = Business.objects.filter(user_relations__user=user)
    
    business_transactions = {}
    for relation in related_business_relations:
        business = relation.business
        transactions = Transaction.objects.filter(business=business).select_related('user')
        business_transactions[business] = transactions

    context = {
        'business_transactions': business_transactions,
        'user_business': related_businesses
    }

    return render(request, "adminScan.html", context)


#APIs
class CreateNormalUserAPIView(APIView):
    """
    API to create 'normal_user' account.
    if it do not recieve an account type, it will set normal_user as a account_type
    """
    parser_classes = [FormParser, MultiPartParser, JSONParser]
    def post(self, request, *args, **kwargs):
        user_data = request.data.dict()
        
        if user_data.get('password') != user_data.get('passwordConfirm'):
            return Response(
                {'error': 'Not same passwords'},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        account_type = user_data.get('account_type', CustomUser.NORMAL_USER)
        if account_type not in [CustomUser.NORMAL_USER, CustomUser.ADMINISTRATOR]:
            return Response(
                {'error': 'Invalid type of account'},
                status=status.HTTP_400_BAD_REQUEST
            )

        name = user_data['first_name']
        last = user_data['last_name']
        user_data['account_type'] = account_type
        def generate_code(business_name, title, business_code):
            business_code_start = business_name[:3].upper()
            random_numbers_1 = ''.join(random.choices(string.digits, k=3))
            title_code = title[:3].upper()
            random_numbers_2 = ''.join(random.choices(string.digits, k=2))
            business_tail = business_code[-3:].upper()

            return f"{business_code_start}{random_numbers_1}{title_code}{random_numbers_2}{business_tail}"
        code = generate_code(name, account_type, last)
        
        
        user_data['code'] = code
        serializer = CustomUserSerializer(data=user_data)
        if serializer.is_valid():
            user = serializer.save()
            code = user_data.get('code', '').strip() 
            if code: 
                try:
                    business = Business.objects.get(code=code)  
                    UserBusinessRelation.objects.create(user=user, business=business) 
                except Business.DoesNotExist:
                    pass
                except Exception as e:
                    pass

            return Response({'message': 'User successfully created.'}, status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
class RewardsAPIView(APIView):
    """
    API to create and delete a new reward for a business.
    only admins of a business can create or delete a new reward
    """
    parser_classes = [FormParser, MultiPartParser, JSONParser]
    
    @method_decorator(user_passes_test(is_admin))  
    def post(self, request, *args, **kwargs):
        user_data = request.data.dict()
        business_id = user_data.get('business')
        title = user_data.get('title', '')
        
        def generate_code(business_name, title, business_code):
            business_code_start = business_name[:3].upper()
            random_numbers_1 = ''.join(random.choices(string.digits, k=3))
            title_code = title[:3].upper()
            random_numbers_2 = ''.join(random.choices(string.digits, k=2))
            business_tail = business_code[-3:].upper()

            return f"{business_code_start}{random_numbers_1}{title_code}{random_numbers_2}{business_tail}"
        
        try:
            business = Business.objects.get(id=business_id)
            business_name = business.name
            business_code = business.code
            
            code = generate_code(business_name, title, business_code)
            user_data['code'] = code
            user_data['business'] = business.id
        except Business.DoesNotExist:
            return Response({'error': 'Business not found.'}, status=status.HTTP_404_NOT_FOUND)

        qr_code_image = generate_qr(code)
        if isinstance(qr_code_image, Response):
            return qr_code_image 
        user_data['qrCode'] = qr_code_image
        
        serializer = RewardSerializer(data=user_data)
        if serializer.is_valid():
            serializer.save()
            return Response({'message': 'New reward created.'}, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    @method_decorator(user_passes_test(is_admin))
    def delete(self, request, *args, **kwargs):
        
        if request.content_type == 'application/json':
            data = JSONParser().parse(request)
        else:
            return Response({'error': 'Unsupported media type'}, status=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE)
        
        reward_id = data.get('reward_id')
        
        try:
            reward = Reward.objects.get(id=reward_id)
            reward.delete() 
            return Response({'message': 'Reward deleted successfully.'}, status=status.HTTP_204_NO_CONTENT)
        except Reward.DoesNotExist:
            return Response({'error': 'Reward not found.'}, status=status.HTTP_404_NOT_FOUND)
        
class CheckCodeApiView(APIView):
    """
    API to add points (post function) or spend points (get function)
    """
    
    @method_decorator(user_passes_test(is_admin))
    def put(self, request, *args, **kwargs):
        code = request.data.get('code')
        username = request.data.get('username')
        
        

        try:
            reward = Reward.objects.get(code=code)
            customer = CustomUser.objects.get(username=username)
            customer_points = UserBusinessRelation.objects.get(user=customer, business=reward.business)
        except Reward.DoesNotExist:
            return Response({'error': 'Reward not found.'}, status=status.HTTP_404_NOT_FOUND)
        except CustomUser.DoesNotExist:
            return Response({'error': 'User not found.'}, status=status.HTTP_404_NOT_FOUND)
        except UserBusinessRelation.DoesNotExist:
            return Response({'error': 'User does not have points with this business.'}, status=status.HTTP_404_NOT_FOUND)

        
        if not UserBusinessRelation.objects.filter(user=request.user, business=reward.business).exists():
            return Response({'error': 'You are not authorized to redeem rewards for this business.'}, status=status.HTTP_403_FORBIDDEN)

        if reward.points_requiered > customer_points.points:
            return Response({'error': 'The user does not have enough points.'}, status=status.HTTP_400_BAD_REQUEST)

        with transaction.atomic():
            customer_points.points -= reward.points_requiered
            customer_points.save()
            Transaction.objects.create(
                title='Points spent',
                amount=reward.points_requiered,
                user=customer,
                business=reward.business
            )

        return Response(status=status.HTTP_200_OK)
    
    @method_decorator(user_passes_test(is_admin))
    def post(self, request, *args, **kwargs):
        print('dede')
        user_code = request.data.get('code')
        business_id = request.data.get('business')
        adding_points = request.data.get('amount')

        try:
            customer = CustomUser.objects.get(code=user_code)
            customer_points = UserBusinessRelation.objects.get(user=customer, business=business_id)
        except CustomUser.DoesNotExist:
            return Response({'error': 'User not found.'}, status=status.HTTP_404_NOT_FOUND)
        except UserBusinessRelation.DoesNotExist:
            return Response({'error': 'User does not have relation with this business.'}, status=status.HTTP_404_NOT_FOUND)


        with transaction.atomic():
            customer_points.points += int(adding_points)
            customer_points.save()
            Transaction.objects.create(
                title='Points added',
                amount=int(adding_points),
                user=customer,
                business= Business.objects.get(id=business_id)
            )

adminPanel/templates/adminIndex.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Admin{% endblock %}</title>

    <!-- SweetAlert2 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <!-- SweetAlert2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- CSS files -->
    <link rel="stylesheet" type="text/css" href="{% static 'adminPanel/css/labels.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'publicPanel/css/colorPalette.css' %}">
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'adminPanel/css/adminIndex.css' %}">
    {% endblock %}

    <!-- Fonts -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Expletus+Sans:wght@400;500;600;700&family=Inter:wght@100;200;300;400;500;600;700;800&display=swap');
    </style>
    <!-- Íconos-->
    <script src="https://kit.fontawesome.com/c986eafe9b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <header>
        <div class="top-menu">
            <div class="top-section">
                <div class="top-logo">
                    <img src="{% static 'publicPanel/svg/main_logo.svg' %}" alt="">
                </div>
                <div class="name-div">
                    <h3>{{ user.username }}</h3>
                </div>
            </div>
            <div class="top-section">
                <a class="log-out" onclick="redirectToLogout()">
                    <i class="fa-solid fa-right-from-bracket"></i>
                </a>
            </div>
        </div>
    </header>

    {% block content %}

    {% for business, rewards in businesses_with_rewards.items %}
    <section class="content">

        <div class="displays">
            <div class="display-rewards">
                <h2>{{ business.name }}</h2>
                <ul class="business-rewards">
                    {% for reward in rewards %}
                    <li>
                        <div class="points-counter">
                            <span class="points-owner">
                                points
                            </span>
                            <span class="points-requiered">
                                requiered
                            </span>
                            <span class="points-requiered">
                                {{ reward.points_requiered }}
                            </span>
                        </div>
                        <hr>
                        <h6>{{ reward.title }}</h6>
                        <p>{{ reward.description }}</p>
                        <button onclick="deleteReward({{ reward.id }})">Delete</button>
                    </li>
                    {% empty %}
                        <li>No rewards available for this business.</li>
                    {% endfor %}
                </ul>
           </div>
    
           <div class="add-reward-panel">
            <h3>Add Reward</h3>
            <form class="personal-info-form" id="add-reward" action="{% url 'adminPanel:rewards-api' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ business.id }}" name="business" id="business">
                <ul class="personal-info-inputs">
                    <li>
                        <div class="input-logo">
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <div class="input-info-label">
                            <label for="title">Title</label>
                            <input type="text" name="title" id="title" maxlength="25" required>
                        </div>
                        <div class="input-pers-logo">
                            <i class="fa-solid fa-pen"></i>
                        </div>
                    </li>
                    <li>
                        <div class="input-logo">
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <div class="input-info-label">
                            <label for="first_name">Points requiered</label>
                            <input type="number" step="1" min="1" name="points_requiered" id="points_requiered">
                        </div>
                        <div class="input-pers-logo">
                            <i class="fa-solid fa-pen"></i>
                        </div>
                    </li>
                    <li>
                        <div class="input-logo">
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <div class="input-info-label">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" maxlength="250">

                            </textarea>
                        </div>
                        <div class="input-pers-logo">
                            <i class="fa-solid fa-pen"></i>
                        </div>
                    </li>
                </ul>
                <div class="add-panel-buttons">
                    <button class="button-settings-form" type="submit">Add</button>
                </div>
            </form>
            <h3>Business info</h3>
            <form class="personal-info-form" id="modify-user" action="" method="post">
                {% csrf_token %}
                <ul class="personal-info-inputs">
                    <li>
                        <div class="input-logo">
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <div class="input-info-label">
                            <label for="business_name">Name</label>
                            <input type="text" value="{{ business.name }}" name="business_name" id="business_name" required readonly>
                        </div>
                        <div class="input-pers-logo">
                            
                        </div>
                    </li>
                    <li>
                        <div class="input-logo">
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <div class="input-info-label">
                            <label for="business_code">Business code</label>
                            <input type="text" value="{{ business.code }}" name="business_code" id="business_code" readonly>
                        </div>
                        <div class="input-pers-logo">
                            
                        </div>
                    </li>

                </ul>
            </form>
           </div>
        </div>

    </section>
    {% endfor %}

    {% endblock %}

    <!-- window -->
    <div id="show-qr" class="modal">
        <div class="modal-contenido">
            <div class="qr-window">
                {% for business in user_business %}
                    <h3 id="title-qr">{{ business.name }}</h3>
                    <img src="{% if business.qrCode %}{{ business.qrCode.url }}{% else %}null{% endif %}" alt="">
                {% endfor %}
                <button onclick="closeQrWindow()">Close</button>
            </div>
        </div>
    </div>

    <footer>
        <div class="bottom-menu">
            <div class="bottom-option" onclick="redirectToHome()">
                <i class="fa-solid fa-house"></i>
            </div>
            <div class="bottom-qr-option" onclick="showQrWindow()">
                <i class="fa-solid fa-qrcode"></i>
            </div>
            <div class="bottom-option" onclick="redirectToScan()">
                <i class="fa-solid fa-expand"></i>
            </div>
        </div>
    </footer>
</body>

<script>
    function redirectToLogout(){
        window.location.href = "{% url 'logout' %}";
    }
    function redirectToHome(){
        window.location.href = "{% url 'adminPanel:home' %}";
    }
    function redirectToScan(){
        window.location.href = "{% url 'adminPanel:scan' %}";
    }
</script>
<script>
    //open window
    function showQrWindow() {
        var modal = document.getElementById("show-qr");
        modal.style.display = "block";
    }
    //close window
    function closeQrWindow() {
        var modal = document.getElementById("show-qr");
        modal.style.display = "none";
    }
</script>
<script type="text/javascript">
    window.csrfToken = "{{ csrf_token }}";
</script>
<script src="{% static 'adminPanel/js/adminIndex.js' %}"></script>

{% block js %}

{% endblock %}
</html>

adminPanel/templates/adminScan.html
{% extends 'adminIndex.html' %}
{% load static %}

    {% block title %}Options{% endblock %}

    {% block css %}
    <script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>

    
    <link rel="stylesheet" type="text/css" href="{% static 'adminPanel/css/adminScan.css' %}">
    {% endblock %}


    {% block content %}

    <section class="content">
        
        <div class="scan-panel">
            <div class="scan-screen" id="scan-screen">
                <button class="change-button" onclick="changeReedem()" id="change-reedem">Change to redeem</button>
                <form class="personal-info-form" id="add-form-scan" action="" method="post">
                    <ul class="personal-info-inputs">
                        <li>
                            <div class="input-logo">
                                <i class="fa-solid fa-user"></i>
                            </div>
                            <div class="input-info-label">
                                <label for="amount">Amount</label>
                                <input type="number" name="amount" id="amount" step="1" min="1" required>
                            </div>
                            <div class="input-pers-logo">
                                <i class="fa-solid fa-pen"></i>
                            </div>
                        </li>
                        <li>
                            <div class="input-logo">
                                <i class="fa-solid fa-user"></i>
                            </div>
                            <div class="input-info-label">
                                <label for="first_name">Business</label>
                                <select id="business" name="business">
                                    {% for business in user_business %}
                                        <option value="{{ business.id }}">{{ business.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="input-pers-logo">
                                <i class="fa-solid fa-pen"></i>
                            </div>
                        </li>
                    </ul>
                </form>
                <form class="personal-info-form" id="reedem-scan" action="" method="post">
                    <ul class="personal-info-inputs">
                        <li>
                            <div class="input-logo">
                                <i class="fa-solid fa-user"></i>
                            </div>
                            <div class="input-info-label">
                                <label for="username">Customer Username</label>
                                <input type="text" name="username" id="username" required>
                            </div>
                            <div class="input-pers-logo">
                                <i class="fa-solid fa-pen"></i>
                            </div>
                        </li>
                    </ul>
                </form>
                <button class="turn-on-scan" id="turn-cam" onclick="scanAction(null)">Turn on</button>
                <div class="scan-square" id="reader">
                    
                </div>
                <span>Choose camera</span>
                <ul class="choose-camera" id="choose-cam">
                    
                </ul>
            </div>
            <ul class="business-transactions">
                {% for business, transactions in business_transactions.items %}
                <span>{{ business.name }}</span>
                    {% for transaction in transactions %}
                    <li>
                        <h6 class="added">{{ transaction.title }}</h6>
                        <div class="points-info">
                            <span>{{ transaction.amount }} points</span>
                            <span>{{ transaction.user.username }}</span>
                            <span>{{ transaction.date|date:"d/m/y" }}</span>
                        </div>
                    </li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
        
    </section>

    {% endblock %}

{% block js %}
<script src="{% static 'adminPanel/js/adminScan.js' %}"></script>

{% endblock %}