TuReward/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from publicPanel import views

urlpatterns = [
    path('adminPage/', admin.site.urls, name='adminPage'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('publicPanel.urls')),
    path('users/', include('userPanel.urls')),
    path('administration/', include('adminPanel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminPanel/urls.py
from django.urls import path

from adminPanel import views
from .views import CreateNormalUserAPIView, RewardsAPIView, CheckCodeApiView, AddBusinessApiView, UpdatePersonalInfoApiView

app_name = 'adminPanel'

urlpatterns = [
    path('',views.index, name="home"),
    path('scan/',views.scan, name="scan"),
    #APIs
    path('create-normal-user/', CreateNormalUserAPIView.as_view(), name='create-normal-user'),
    path('rewards-api/', RewardsAPIView.as_view(), name='rewards-api'),
    path('check-code-api/', CheckCodeApiView.as_view(), name='check-code-api'),
    path('add-business-api/', AddBusinessApiView.as_view(), name='add-business-api'),
    path('update-personal-info-api/', UpdatePersonalInfoApiView.as_view(), name='update-personal-info-api'),
]

userPanel/urls.py
from django.urls import path

from userPanel import views


app_name = 'userPanel'

urlpatterns = [
    path('',views.userIndex, name="home"),
    path('options/',views.userOptions, name="options"),
    
    
]

userPanel/models.py
from django.db import models

# Create your models here.

userPanel/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from adminPanel.models import CustomUser, UserBusinessRelation, Reward, Transaction

def is_admin(user):
    return user.is_authenticated and user.account_type == 'administrator'

def is_normal(user):
    return user.is_authenticated and user.account_type == 'normal_user'

@user_passes_test(is_normal)
def userIndex(request):
    user = request.user
    
    # Obtén las relaciones de negocios del usuario
    user_business_relations = UserBusinessRelation.objects.filter(user=user)
    
    # Crea un diccionario para almacenar los negocios, recompensas y puntos
    businesses_data = []
    
    for relation in user_business_relations:
        business = relation.business
        rewards = business.rewards.all()
        transactions = Transaction.objects.filter(user=user, business=business)
        
        # Obtén los puntos del usuario para este negocio
        points = relation.points
        
        # Agregar los datos al diccionario
        businesses_data.append({
            "business": business,
            "rewards": rewards,
            "transactions": transactions,
            "points": points,
        })
    
    # Pasar los datos al contexto
    context = {
        "user": user,
        "businesses_data": businesses_data,
    }

    return render(request, "userIndex.html", context)

@user_passes_test(is_normal)
def userOptions(request):
    context = {
        'user': request.user,
    }
    return render(request, "userOptions.html", context)

userPanel/templates/userIndex.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>

    <!-- SweetAlert2 CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <!-- SweetAlert2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- CSS files -->
    <link rel="stylesheet" type="text/css" href="{% static 'userPanel/css/labels.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'publicPanel/css/colorPalette.css' %}">
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'userPanel/css/userIndex.css' %}">
    {% endblock %}

    <!-- Fonts -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Expletus+Sans:wght@400;500;600;700&family=Inter:wght@100;200;300;400;500;600;700;800&display=swap');
    </style>
    <!-- Íconos-->
    <script src="https://kit.fontawesome.com/c986eafe9b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <header>
        <div class="top-menu">
            <div class="top-section">
                <div class="top-logo">
                    <img src="{% static 'publicPanel/svg/main_logo.svg' %}" alt="">
                </div>
                <div class="name-div">
                    <h3>{{ user.username }}</h3>
                </div>
            </div>
            <div class="top-section">
                <a class="log-out" onclick="redirectToLogout()">
                    <i class="fa-solid fa-right-from-bracket"></i>
                </a>
            </div>
        </div>
    </header>

    {% block content %}

    <section class="content">
        
        <ul class="business-list">
            {% for business_data in businesses_data %}
                <li class="business-info">
                    <div class="top-business-info">
                        <h5>{{ business_data.business.name }}</h5>
                        <span>since {{ business_data.business.created_at|date:"d/m/y" }}</span>
                    </div>
                    
                    <ul class="business-rewards">
                        {% for reward in business_data.rewards %}
                            <li>
                                <div class="points-counter">
                                    <span class="points-owner">{{ business_data.points }}</span>
                                    <span class="points-requiered">of</span>
                                    <span class="points-requiered">{{ reward.points_requiered }}</span>
                                </div>
                                <hr>
                                <h6>{{ reward.title }}</h6>
                                <p>{{ reward.description }}</p>
                                <button onclick="showQrWindow('{% if reward.qrCode %}{{ reward.qrCode.url }}{% else %}null{% endif %}', '{{ reward.title }}')">Get</button>
                            </li>
                        {% endfor %}
                    </ul>
                    
                    <ul class="business-transactions">
                        <span>Transactions</span>
                        {% for transaction in business_data.transactions %}
                            <li>
                                <h6 class="{% if transaction.amount > 0 %}added{% else %}spent{% endif %}">
                                    {% if transaction.amount > 0 %}Points Added{% else %}Points Spent{% endif %}
                                </h6>
                                <div class="points-info">
                                    <span>{{ transaction.amount }} points</span>
                                    <span>{{ transaction.date|date:"d/m/y" }}</span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
        
        
    </section>

    {% endblock %}

    <!-- window -->
    <div id="show-qr" class="modal">
        <div class="modal-contenido">
            <div class="qr-window">
                <h3 id="title-qr"></h3>
                <img id="img-id" src="" alt="">
                <button onclick="closeQrWindow()">Close</button>
            </div>
        </div>
    </div>

    <footer>
        <div class="bottom-menu">
            <div class="bottom-option" onclick="redirectToHome()">
                <i class="fa-solid fa-house"></i>
            </div>
            <div class="bottom-qr-option" onclick="showQrWindow('{% if user.qrCode %}{{ user.qrCode.url }}{% else %}null{% endif %}', 'User QR')">
                <i class="fa-solid fa-qrcode"></i>
            </div>
            <div class="bottom-option" onclick="redirectToOptions()">
                <i class="fa-solid fa-bars"></i>
            </div>
        </div>
    </footer>
</body>

<script>
    function redirectToLogout(){
        window.location.href = "{% url 'logout' %}";
    }
    function redirectToHome(){
        window.location.href = "{% url 'userPanel:home' %}";
    }
    function redirectToOptions(){
        window.location.href = "{% url 'userPanel:options' %}";
    }
</script>
<script>
    //open window
    function showQrWindow(code, content) {
        document.getElementById("title-qr").textContent = content;
        document.getElementById("img-id").src = code;

        var modal = document.getElementById("show-qr");
        modal.style.display = "block";
    }
    //close window
    function closeQrWindow() {
        var modal = document.getElementById("show-qr");
        modal.style.display = "none";
    }
</script>
<script type="text/javascript">
    window.csrfToken = "{{ csrf_token }}";
</script>
{% block js %}

{% endblock %}
</html>

userPanel/templates/userOptions.html
{% extends 'userIndex.html' %}
{% load static %}

    {% block title %}Options{% endblock %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'userPanel/css/userOptions.css' %}">
    {% endblock %}


    {% block content %}

    <section class="content">
        <h3 class="form-title">Add business</h3>
        <form class="personal-info-form" id="add-business" action="{% url 'adminPanel:add-business-api' %}" method="post">
            {% csrf_token %}
            <ul class="personal-info-inputs">
                <li>
                    <div class="input-logo">
                        <i class="fa-solid fa-key"></i>
                    </div>
                    <div class="input-info-label">
                        <label for="username">Business CODE</label>
                        <input type="text" name="code" id="businessCode" required>
                    </div>
                    <div class="input-pers-logo">
                        <i class="fa-solid fa-pen"></i>
                    </div>
                </li>
                
            </ul>
            <div class="add-panel-buttons">
                <button class="button-settings-form" type="submit">Add</button>
            </div>
            
        </form>

        <h3 class="form-title">Personal info</h3>
        <form class="personal-info-form" id="modify-user" action="{% url 'adminPanel:update-personal-info-api' %}" method="post">
            {% csrf_token %}
            <ul class="personal-info-inputs">
                <li>
                    <div class="input-logo">
                        <i class="fa-solid fa-user"></i>
                    </div>
                    <div class="input-info-label">
                        <label for="username">Username</label>
                        <input type="text" name="username" value="{{ user.username }}" id="usernameM" required readonly>
                    </div>
                    <div class="input-pers-logo">
                        <i class="fa-solid fa-pen"></i>
                    </div>
                </li>
                <li>
                    <div class="input-logo">
                        <i class="fa-solid fa-user"></i>
                    </div>
                    <div class="input-info-label">
                        <label for="first_name">Name</label>
                        <input type="text" value="{{ user.first_name }}" name="first_name" id="first_nameM" required>
                    </div>
                    <div class="input-pers-logo">
                        <i class="fa-solid fa-pen"></i>
                    </div>
                </li>
                <li>
                    <div class="input-logo">
                        <i class="fa-solid fa-user"></i>
                    </div>
                    <div class="input-info-label">
                        <label for="last_name">Last name</label>
                        <input type="text" value="{{ user.last_name }}" name="last_name" id="last_nameM" required>
                    </div>
                    <div class="input-pers-logo">
                        <i class="fa-solid fa-pen"></i>
                    </div>
                </li>
                <li>
                    <div class="input-logo">
                        <i class="fa-solid fa-phone"></i>
                    </div>
                    <div class="input-info-label">
                        <label for="phone_number">Phone</label>
                        <input type="tel" value="{{ user.phone_number }}" name="phone_number" id="phone_numberM">
                    </div>
                    <div class="input-pers-logo">
                        <i class="fa-solid fa-pen"></i>
                    </div>
                </li>
                <li>
                    <div class="input-logo">
                        <i class="fa-solid fa-envelope"></i>
                    </div>
                    <div class="input-info-label">
                        <label for="email">Email</label>
                        <input type="email" value="{{ user.email }}" name="email" id="emailM" required>
                    </div>
                    <div class="input-pers-logo">
                        <i class="fa-solid fa-pen"></i>
                    </div>
                </li>
            </ul>
            <div class="add-panel-buttons">
                <button class="button-settings-form" type="submit">Modify</button>
            </div>
            
        </form>
    </section>

    {% endblock %}

{% block js %}
<script src="{% static 'userPanel/js/userOptions.js' %}"></script>
{% endblock %}