TuReward/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from publicPanel import views

urlpatterns = [
    path('adminPage/', admin.site.urls, name='adminPage'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('publicPanel.urls')),
    path('users/', include('userPanel.urls')),
    path('administration/', include('adminPanel.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminPanel/urls.py
from django.urls import path

from adminPanel import views
from .views import CreateNormalUserAPIView, RewardsAPIView, CheckCodeApiView, AddBusinessApiView, UpdatePersonalInfoApiView

app_name = 'adminPanel'

urlpatterns = [
    path('',views.index, name="home"),
    path('scan/',views.scan, name="scan"),
    #APIs
    path('create-normal-user/', CreateNormalUserAPIView.as_view(), name='create-normal-user'),
    path('rewards-api/', RewardsAPIView.as_view(), name='rewards-api'),
    path('check-code-api/', CheckCodeApiView.as_view(), name='check-code-api'),
    path('add-business-api/', AddBusinessApiView.as_view(), name='add-business-api'),
    path('update-personal-info-api/', UpdatePersonalInfoApiView.as_view(), name='update-personal-info-api'),
]

publicPanel/urls.py
from django.urls import path

from publicPanel import views


app_name = 'publicPanel'

urlpatterns = [
    path('',views.index, name="home"),
    path('signUp/',views.signUp, name="signUp"),
    path('redirectPanel/',views.redirect_panel, name="redirectPanel"),
    
    #APIs
    path('usersApi/',views.usersApi, name="users-api"),
    
]

publicPanel/models.py
from django.db import models

# Create your models here.

publicPanel/views.py
from django.shortcuts import render
from rest_framework import serializers
from django.shortcuts import redirect

def index(request):
    
    return render(request, "index.html")

def signUp(request):
    
    return render(request, "create_account.html")

def redirect_panel(request):
    user = request.user
    if user.account_type == 'administrator':
        return redirect('adminPanel:home')
    if user.account_type == 'normal_user':
        return redirect('userPanel:home')

    
    

#APIs
def usersApi(request):
    
    return render(request, "create_account.html")

publicPanel/templates/create_account.html
{% load static %}
<!DOCTYPE html>
<html lang="en"></html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sign Up</title>
        
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <!-- CSS files -->
        <link rel="stylesheet" type="text/css" href="{% static 'publicPanel/css/colorPalette.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'publicPanel/css/create_account.css' %}">
        <!-- Fonts -->
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Expletus+Sans:wght@400;500;600;700&family=Inter:wght@100;200;300;400;500;600;700;800&display=swap');
        </style>
        <!-- Íconos-->
        <script src="https://kit.fontawesome.com/c986eafe9b.js" crossorigin="anonymous"></script>
        <!-- Ícono -->
        <link rel="icon" type="image/png" href="{% static 'publicPanel/svg/icon_TuReward.svg' %}">
    </head>
<body>
    <header class="title-page">
        <h1>Sign Up</h1>
    </header>
    <section class="account_section">
        <div class="panel">
            <div onclick="redirectToHome()" class="logo-panel">
                <img src="{% static 'panammun_panel/svg/icon_panammun.svg' %}" alt="">
            </div>
            <div class="text-panel">
                <h2>Tu Reward</h2>
            </div>
            <div class="main-panel">
                <form class="main-form" id="user-form" method="post" enctype="multipart/form-data" action="{% url 'adminPanel:create-normal-user' %}">
                    {% csrf_token %}
                    <ul>
                        <div class="two-inputs">
                            <li style="margin-right: .5em;">
                                <label for="full_name">Name</label>
                                <div class="top-input">
                                    <input type="text" name="first_name" placeholder="Enter your name" maxlength="30" required>
                                    <i class="fa-solid fa-user"></i>
                                </div>
                                <hr>
                            </li>
                            <li style="margin-left: .5em;">
                                <label for="full_name">Last name</label>
                                <div class="top-input">
                                    <input type="text" name="last_name" maxlength="50" placeholder="Enter your last name" required>
                                    <i class="fa-solid fa-user"></i>
                                </div>
                                <hr>
                            </li>
                        </div>
                        <div class="two-inputs">
                            <li style="margin-right: .5em;">
                                <label for="username">Username</label>
                                <div class="top-input">
                                    <input type="text" name="username" placeholder="Create username" autocomplete="new-username" maxlength="20" required>
                                    <input type="hidden" name="account_type" value="normal_user">
                                    <i class="fa-solid fa-circle-user"></i>
                                </div>
                                <hr>
                            </li>
                            <li style="margin-left: .5em;">
                                <label for="full_name">Phone (optional)</label>
                                <div class="top-input">
                                    <input type="tel" name="phone_number" maxlength="15" placeholder="Enter phone number">
                                    <i class="fa-solid fa-phone"></i>
                                </div>
                                <hr>
                            </li>
                        </div>
                        <li>
                            <label for="email">Email</label>
                            <div class="top-input">
                                <input type="email" name="email" placeholder="Enter email" required>
                                <i class="fa-solid fa-envelope"></i>
                            </div>
                            <hr>
                        </li>
                        <div class="two-inputs">
                            <li style="margin-right: .5em;">
                                <label for="password">Password</label>
                                <div class="top-input">
                                    <input type="password" id="password" name="password" minlength="8" placeholder="Create password" autocomplete="new-password" required>
                                    <i class="fa-solid fa-lock"></i>
                                </div>
                                <hr>
                            </li>
                            <li style="margin-left: .5em;">
                                <label for="password">Repeat Password</label>
                                <div class="top-input">
                                    <input type="password" id="password2" name="passwordConfirm" minlength="8" placeholder="Repeat password" autocomplete="new-password" required>
                                    <i class="fa-solid fa-lock"></i>
                                </div>
                                <hr>
                            </li>
                        </div>
                        <li>
                            <label for="email">Business code (optional)</label>
                            <div class="top-input">
                                <input type="text" name="code" placeholder="Enter business code (optional)">
                                <i class="fa-solid fa-barcode"></i>
                            </div>
                            <hr>
                        </li>
                    </ul>
                    <p class="errorM">
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <span class="error-message">{{ error|escape }}</span>
                                {% endfor %}
                            {% endfor %}
                    
                            {% for error in form.non_field_errors %}
                                <span class="error-message">{{ error|escape }}</span>
                            {% endfor %}
                        {% endif %}
                    </p>
                    <button type="submit">Create</button>
                </form>
                <div class="no-account">
                    <span>Already have account? </span><span><a href="{% url 'login' %}">Sign in</a></span>
                </div>
            </div>
        </div>
    </section>
</body>
<!-- JS files -->
<script src="{% static 'publicPanel/js/create_account.js' %}"></script>
<script type="text/javascript">
    window.csrfToken = "{{ csrf_token }}";
</script>
<script>
    function redirectToHome(){
        window.location.href = "{% url 'publicPanel:home' %}";
    }
</script>

</html>

publicPanel/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TuReward</title>
    <!-- CSS files -->
    <link rel="stylesheet" type="text/css" href="{% static 'publicPanel/css/colorPalette.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'publicPanel/css/index.css' %}">

    <!-- Fonts -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Expletus+Sans:wght@400;500;600;700&family=Inter:wght@100;200;300;400;500;600;700;800&display=swap');
    </style>
    <!-- Icons -->
    <script src="https://kit.fontawesome.com/c986eafe9b.js" crossorigin="anonymous"></script>
    
    <!-- Ícono -->
    <link rel="icon" type="image/png" href="{% static 'publicPanel/svg/main_logo.svg' %}">
</head>

<body>
    <header class="nav-bar">
        <div class="nav-panel">
            <a class="main-logo-name" href="#">
                <img class="main-logo" src="{% static 'publicPanel/svg/main_logo.svg' %}" alt="">
                <h2 class="main-tittle-nav">TuReward</h2>
            </a>
            <div class="right-nav">
                <div class="list-button" onclick="navButton()">
                    <i class="fa-solid fa-bars"></i>
                </div>
                <div id="options-nav" class="sections-nav">
                    <li onclick="redirectToDAG()">DAG</li>
                    <li onclick="">Contact</li>
                    <li onclick="redirectToLogin()">Login</li>
                </div>
            </div>


        </div>
    </header>
    <section class="first-section">
        <div class="main-part">
            <div class="div-part-left">
                <h1 class="main-tittle">Your <span class="h1-fat">Loyalty</span> always <span
                        class="h1-fat">Rewarded</span>
                </h1>
                <p class="main-info"><span class="p-fat">TuReward</span> is a digital loyalty system designed for businesses like restaurants and cafés to enhance customer retention. With QR code technology, customers can earn points for their purchases and redeem them for exclusive rewards. Easy to use, customizable, and efficient, TuReward transforms regular visits into
                    <span class="p-fat">rewarding experiences.</span>
                </p>
                <button class="main-contact-button" onclick="scrollToContact()">Contact Us</button>
            </div>
            <div class="div-part-right">
                <img src="{% static 'publicPanel/svg/main-views.svg' %}" alt="">
            </div>
        </div>
    </section>
        <footer>
          <div class="footer-container">
            <p class="log">
                <img src="{% static 'residevAPP/svg/ResiDEV_complete_main_logo.svg' %}" alt="" title="AQRI">
              <span class="by">&nbsp;by</span>
              <span style="color: #00866b; font-weight: 600; font-size: 1.3em;">DAG</span>
              <span style="color: var(--text-100); font-weight: 600; font-size: 1.3em;">DEV</span>
            </p>
    
            <p class="website" onclick="redirectToDAG()">Website by <span style="color: var(--text-100); transition:.5s;">DAG</span></p>
        </div>
        </footer>
</body>

<script>
    function redirectToDAG() {
        window.location.href = "https://www.dagcorp.dev";
    }
    function redirectToLogin() {
        window.location.href = "{% url 'login' %}";
    }

    //NAVBAR
window.addEventListener("scroll", function() {
    var navBar = document.querySelector(".nav-bar");
    if (window.scrollY > 0) {
        navBar.classList.add("nav-bar-scroll");
    } else {
        navBar.classList.remove("nav-bar-scroll");
    }
});

function navButton() {
    var options = document.getElementById('options-nav');
    var navPanel = document.querySelector('.nav-panel');
    var listButton = document.querySelector('.list-button');
  
    if (options.style.display === 'flex') {
      options.style.display = 'none';
      navPanel.style.alignItems = 'initial';
      listButton.style.display = 'block'; 
    } else {
      options.style.display = 'flex';
      navPanel.style.alignItems = 'baseline';
      listButton.style.display = 'none'; 
    }
  }
  
  
  window.addEventListener('scroll', function(event) {
    if (window.innerWidth < 600) {
      var options = document.getElementById('options-nav');
      var navPanel = document.querySelector('.nav-panel');
      var listButton = document.querySelector('.list-button');
  
      // Si el scroll no ocurrió en el nav-panel
      
        options.style.display = 'none';
        navPanel.style.alignItems = 'initial';
        listButton.style.display = 'block'; // Restaurar el display
      
    }
  });

  
</script>

</html>